# Generated by Django 3.1.7 on 2021-03-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
    ]
